### ISSUE TITLE
Pros and cons of this over https://github.com/catalyst/moodle-tool_objectfs

### ISSUE THREAD

**Issue by brendanheywood** [EduardoKrausME/moodle-local_alternative_file_system#1]
hi @eduardokraus 

Just curious what the pros and cons are for this plugin over:

https://github.com/catalyst/moodle-tool_objectfs

**Comment by eduardokraus** [comment]
## Pros:

1. **Installation Simplicity**: 
    - With just one plugin to install, the installation process is quick and straightforward, saving time and effort.
1. **Ease of Configuration**: 
    - The self-intuitive interface makes configuration a simple task, free from common errors.
1. **Error-free Installation**: 
    - Installing the plugin won't encounter errors such as the absence of the file_system class.
1. **SDK Version Independence**: 
    - Including SDKs within the plugin eliminates concerns about version incompatibilities, providing smooth integration free from complications.
1. **Implementation Flexibility**: 
    - The ease of adding other storage methods expands available options, allowing for more efficient adaptation to project-specific needs.
1. **Simplicity in Configuration**: 
    - With just one line to add to the config.php file, the integration process is simplified, reducing potential errors and easing future maintenance.

## Cons:

- **Provider Limitation**: 
    - The limited availability of storage providers, such as AWS, Digital Ocean (the one I needed), and Google Cloud Storage, may restrict options and flexibility depending on project requirements.
- **Internet Connection Dependency**: 
    - Proper plugin functioning is contingent upon a stable connection between the server and storage.
- **Associated Costs**: 
    - Using cloud storage services typically involves variable costs, such as usage and storage fees, which must be considered in the project's financial planning.
